# Generated by Django 5.2 on 2025-05-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0003_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
