# Generated by Django 5.2 on 2025-04-06 13:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('experience', models.CharField(choices=[('1-2', '1-2 years'), ('3-5', '3-5 years'), ('5+', '5+ years')], max_length=10)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('portfolio', models.URLField(blank=True, null=True)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
    ]
